package com.patecan.report_processing.aws_processor.data.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.*;

import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;

@Data
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
@DynamoDBTable(tableName = "dev-cta-CustomersTable-7TWZ72UTKZJV")
public class CompositionCustomerEntity {

    @DynamoDBHashKey
    @DynamoDBAttribute(attributeName = "id")
    String id;

    @DynamoDBHashKey
    @DynamoDBAttribute(attributeName = "customerSortKey")
    String customerSortKey;

    @DynamoDBAttribute(attributeName = "createdAt")
    private String createdAt=getFormattedCurrentTime();

    @DynamoDBAttribute(attributeName = "mostRecentOrderFood")
    private String mostRecentOrderFood="";

    @DynamoDBAttribute(attributeName = "mostRecentOrderTime")
    private String mostRecentOrderTime="";

    @DynamoDBAttribute(attributeName = "customerName")
    private String customerName="";

    @DynamoDBAttribute(attributeName = "customerNamePrefix")
    private String customerNamePrefix="";

    @DynamoDBAttribute(attributeName = "phoneNumber")
    private String phoneNumber="";

    @DynamoDBAttribute(attributeName = "updatedAt")
    private String updatedAt=getFormattedCurrentTime();


    private String getFormattedCurrentTime() {
        ZonedDateTime now = ZonedDateTime.now();
        return now.format(DateTimeFormatter.ISO_INSTANT);
    }



}

